import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val android_arch_navigation: String = "2.1.0"

    const val com_trello_rxlifecycle3: String = "3.0.0" // available: "3.1.0"

    const val com_squareup_retrofit2: String = "2.5.0" // available: "2.6.2"

    const val org_jetbrains_kotlin: String = "1.3.61"

    const val androidx_lifecycle: String = "2.1.0"

    const val org_jetbrains_anko: String = "0.10.4" // available: "0.10.8"

    const val android_arch_work: String = "1.0.0-alpha02" // available: "1.0.1"

    const val androidx_multidex: String = "2.0.0"

    const val com_google_dagger: String = "2.19" // available: "2.25.2"

    const val com_j256_ormlite: String = "5.0" // available: "5.1"

    const val com_jakewharton: String = "10.0.0" // available: "10.2.0"

    const val androidx_test: String = "1.1.0" // available: "1.2.0"

    const val org_mockito: String = "2.16.0" // available: "3.2.0"

    const val com_android_tools_build_gradle: String = "3.5.2"

    const val com_madgag_spongycastle_core: String = "1.56.0.0" // available: "1.58.0.0"

    const val io_fabric_tools_gradle: String = "1.27.1" // available: "1.31.2"

    const val com_github_ben_manes_versions_gradle_plugin: String = "0.27.0"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val picasso2_okhttp3_downloader: String = "1.1.0"

    const val retrofit2_rxjava2_adapter: String = "1.0.0"

    const val play_services_analytics: String = "16.0.0" // available: "17.0.0"

    const val expandablerecyclerview: String = "1.3" // available: "1.4"

    const val play_services_location: String = "15.0.1" // available: "17.0.0"

    const val okhttp_urlconnection: String = "3.8.1" // available: "4.2.2"

    const val play_services_vision: String = "15.0.1" // available: "19.0.0"

    const val logging_interceptor: String = "3.8.1" // available: "4.2.2"

    const val android_maps_utils: String = "0.5" // available: "0.6.2"

    const val firebase_messaging: String = "17.0.0" // available: "20.0.1"

    const val legacy_support_v13: String = "1.0.0"

    const val play_services_auth: String = "15.0.1" // available: "17.0.0"

    const val play_services_base: String = "15.0.1" // available: "17.1.0"

    const val play_services_maps: String = "15.0.1" // available: "17.0.0"

    const val play_services_gcm: String = "15.0.1" // available: "17.0.0"

    const val sqliteassethelper: String = "2.0.1"

    const val constraintlayout: String = "1.1.3"

    const val advrecyclerview: String = "1.0.0"

    const val firebase_config: String = "16.0.0" // available: "19.0.3"

    const val google_services: String = "4.3.3"

    const val exoplayer_core: String = "2.9.6" // available: "2.10.8"

    const val exoplayer_dash: String = "2.9.6" // available: "2.10.8"

    const val mockito_kotlin: String = "1.5.0"

    const val espresso_core: String = "3.2.0"

    const val exoplayer_hls: String = "2.9.6" // available: "2.10.8"

    const val firebase_core: String = "16.0.0" // available: "17.2.1"

    const val gradle_plugin: String = "0.12.0"

    const val mockwebserver: String = "3.9.1" // available: "4.2.2"

    const val okhttp_digest: String = "1.18" // available: "2.0"

    const val core_testing: String = "2.1.0"

    const val exoplayer_ui: String = "2.9.6" // available: "2.10.8"

    const val recyclerview: String = "1.1.0"

    const val crashlytics: String = "2.6.7" // available: "2.10.1"

    const val lint_gradle: String = "26.5.2"

    const val robolectric: String = "4.3.1"

    const val simple_xml: String = "2.7.1"

    const val analytics: String = "4.2.6" // available: "4.3.1"

    const val appcompat: String = "1.1.0"

    const val exoplayer: String = "r1.5.10" // available: "2.10.8"

    const val joda_time: String = "2.9.9" // available: "2.10.5"

    const val rxandroid: String = "2.1.1"

    const val material: String = "1.1.0-alpha01"

    const val rxkotlin: String = "2.4.0"

    const val apache_net: String = "3.6"

    const val picasso: String = "2.5.2" // available: "2.71828"

    const val okhttp: String = "3.8.1" // available: "4.2.2"

    const val rxjava: String = "2.2.15"

    const val timber: String = "4.7.1"

    const val aapt2: String = "3.5.2-5435860"

    const val jsoup: String = "1.10.2" // available: "1.12.1"

    const val junit: String = "4.12"

    const val bran: String = "1.3.5"

    const val gson: String = "2.8.6"

    const val otto: String = "1.3.8"

    const val pkix: String = "1.54.0.0"

    const val prov: String = "1.56.0.0" // available: "1.58.0.0"

    const val pg: String = "1.54.0.0"

    /**
     * Current version: "5.4.1"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.0.1"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
