import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val android_arch_navigation: String = "2.1.0"

    const val com_trello_rxlifecycle3: String = "3.0.0" // available: "3.1.0"

    const val com_squareup_retrofit2: String = "2.5.0" // available: "2.6.2"

    const val org_jetbrains_kotlin: String = "1.3.61"

    const val androidx_lifecycle: String = "2.1.0"

    const val androidx_multidex: String = "2.0.0"

    const val com_google_dagger: String = "2.24" // available: "2.25.2"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val picasso2_okhttp3_downloader: String = "1.1.0"

    const val retrofit2_rxjava2_adapter: String = "1.0.0"

    const val okhttp_urlconnection: String = "3.8.1" // available: "4.2.2"

    const val logging_interceptor: String = "3.8.1" // available: "4.2.2"

    const val constraintlayout: String = "1.1.3"

    const val recyclerview: String = "1.1.0"

    const val appcompat: String = "1.1.0"

    const val rxandroid: String = "2.1.1"

    const val material: String = "1.1.0-alpha01"

    const val rxkotlin: String = "2.4.0"

    const val picasso: String = "2.5.2" // available: "2.71828"

    const val okhttp: String = "3.8.1" // available: "4.2.2"

    const val rxjava: String = "2.2.15"

    const val timber: String = "4.7.1"

    const val junit: String = "4.12"
    const val gson: String = "2.8.6"

    /**
     * Current version: "5.4.1"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.0.1"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
