name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Bundle Install
        run: bundle install
      - name: Bundle update
        run: bundle update
      - name: Bundle update fastlane
        run: bundle update fastlane
      - name: Run a multi-line script
        run: bundle exec fastlane build
